version: "2.1"
services:
  kassoubot:
    image: mylloon/kassoubot
    container_name: KassouBot
    environment:
      - TOKEN_DISCORD=yourTokenDiscord
      - TOKEN_GENIUS=yourTokenGenius
      - TOKEN_REDDIT_CLIENT_ID=yourRedditClientID
      - TOKEN_REDDIT_CLIENT_SECRET=yourRedditClientSecret
      - TOKEN_REDDIT_USER_AGENT=yourRedditUserAgent
      - TIMEZONE=yourTimezone # More info here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - PREFIX=yourPrefix
    volumes:
      - /here/your/path/:/src/db/
    restart: unless-stopped
